owner: MigraineKR
repo: ahs.status

sites:
  - name: americanheadachesociety.org
    url: https://americanheadachesociety.org/
  - name: americanmigrainefoundation.org
    url: https://americanmigrainefoundation.org/
        
status-website:
  cname: ahs.status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | AHS
  introTitle: "**Status** for American Headache Society"
  introMessage: American Headache Society WebMonitor
  navbar:
    - title: Website
      href: https://americanheadachesociety.org/
    - title: YouTube
      href: https://www.youtube.com/@ahshq
    - title: Twitter
      href: https://twitter.com/ahsheadache
    - title: Instagram
      href: https://www.instagram.com/ahsheadache/
    - title: Facebook
      href: https://www.facebook.com/ahsheadache
